parameters:
- name: Solution
  type: string
  default: ''
- name: ArtifactName
  type: string
  default: ''

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '8.0.0'

- task: unoplatformCanaryUpdater@1
  inputs:
    solution: ${{ parameters['Solution'] }}
    usePrivateFeed: false
    useNuGetOrg: true
    mergeBranch: true
    branchToMerge: 'master'
    nugetUpdaterVersion: '1.1.0'
    allowDowngrade: true
    packageAuthor: 'nventive'
    summaryFile: '$(Build.ArtifactStagingDirectory)/Summary.md'
    resultFile: '$(Build.ArtifactStagingDirectory)/Results.json'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: ${{ parameters['ArtifactName'] }}