jobs:
- job: Windows
  
  pool:
    vmImage: windows-2022

  variables:
    Solution: CSharp\Uno\Uno.RayTraceBenchmark.sln
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  steps:
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries') }}:
    - template: .vsts-ci.canaries.yml
      parameters:
        Solution: $(Solution)
        ArtifactName: Canaries

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.202'

  - task: gitversion/setup@0
    retryCountOnTaskFailure: 3
    inputs:
      versionSpec: '5.10.3'
    displayName: 'Install GitVersion'
  
  - task: gitversion/execute@0
    retryCountOnTaskFailure: 3
    inputs:
      useConfigFile: true
      configFilePath: 'gitversion.yml'
    displayName: 'Calculate SemVer'

  - pwsh: |
      echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
      echo "##vso[task.setvariable variable=JavaSdkDirectory]$(JAVA_HOME_11_X64)"
    displayName: Select JDK 11

  - task: MSBuild@1
    inputs:
      solution: $(Solution)
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:InformationalVersion=$(GitVersion.InformationalVersion)" /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: 'CSharp\Uno\RayTraceBenchmark\RayTraceBenchmark.Wasm\bin\Release\net7.0\dist'
      artifactType: container
      artifactName: RayTraceBenchmark-Wasm

- job: Linux
  container: unoplatform/wasm-build:3.0

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    NUGET_PACKAGES: $(Build.SourcesDirectory)/.nuget
    Solution: 

  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.203'

  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries') }}:
    - template: .vsts-ci.canaries.yml
      parameters:
        Solution: $(Build.SourcesDirectory)/CSharp/Uno/Uno.RayTraceBenchmark.sln
        ArtifactName: Canary-AOT

  - task: UseDotNet@2
    displayName: 'Use .Net Core runtime 5.0.3'
    inputs:
      packageType: runtime
      version: 5.0.3

  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.6.8'

  - task: gitversion/execute@0
    inputs:
      updateAssemblyInfo: 'False'
      useConfigFile: true
      configFilePath: gitversion.yml
    displayName: Use GitVersion

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 5.0.203

  - bash: |
      dotnet build -f net8.0-browserwasm -v Release "/p:InformationalVersion=$(GitVersion.InformationalVersion)" "$(Build.SourcesDirectory)/CSharp/Uno/RayTraceBenchmark/RayTraceBenchmark/RayTraceBenchmark.csproj"

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/CSharp/Uno/RayTraceBenchmark/RayTraceBenchmark.Wasm/bin/Release/net7.0/dist'
      Contents: '**/*.*'
      TargetFolder: $(Build.ArtifactStagingDirectory)/wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: aot-drop
      ArtifactType: Container
